### ISSUE TITLE
Change StackLayout's wrap to nowrap

### ISSUE THREAD

**Issue by philmirez** [auth0/cosmos#1535]
I get that the `wrap` property for the StackLayout is a boolean. But, the values seem to mismatch. I would think if the `wrap` property exists then the boolean value would be true. However, after digging and reading some of the other issues and documentation I see the intention is to wrap by default.

Since `nowrap` is being rendered for `flex-wrap` when `wrap` is specified, I think it would be better if the property was `nowrap` instead of `wrap`.

At first, this was not straight forward so I left the `wrap` property off and ended up explicitly specifying it. It didn't dawn on me until I started playing around with the documentation a little more.

It makes sense now, because I see on the documentation the toggle is false by default. But, initially it was misleading.

**Comment by francocorreasosa** [comment]
Hey @7IHd 👋 Thank you for taking the time to report this.

@andresgalante what do you think?

**Comment by andresgalante** [comment]
Hi @7IHd thanks for reporting this. I see what you mean it can be misleading.

When we first created StackLayout the default was set to `nowrap`, when we changed it we forgot to change the prop.

Changing the prop name to `nowrap` makes sense. if it's on then the layout will prevent wrapping, by default it'll be off.

@francocorreasosa @cristiandouce this means a breaking change, but since the layouts are so new I don't know if it'll have a real impact. Can we do this now?
