### ISSUE TITLE
Some links on the docs page give 404

### ISSUE THREAD

**Issue by konradsopala** [auth0/cosmos#1739]
**Describe the bug**
Some links on https://auth0-cosmos.now.sh/#/usage are broken (give 404). For example:

* Installation
* Using component
* Building your own components
* Usage with styleguide

**Expected behavior**
They should open.

**Screenshots**
None

**Cosmos version:**
It's about cosmos docs not cosmos itself

**Additional context**

**Comment by harshcut** [comment]
The page is routed to [/docs/#/usage#installation](https://auth0-cosmos.vercel.app/docs/#/usage#installation) instead of [/#/usage#installation](https://auth0-cosmos.vercel.app/#/usage#installation).

https://github.com/auth0/cosmos/blob/8d5e2f34f818db8f245f52abb8bffc5f853ea4b5/internal/docs/docs-components/folding-section.js#L20-L27

**Comment by theinfosecguy** [comment]
Looks like a lot of pages are broken due to [this](https://auth0-cosmos.vercel.app/docs/#/contribution-guide) including **_Contribution Guide_**.
