### ISSUE TITLE
Proposal: Documentation technique for compound components

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#200]
Here's the problem with compound components:

They have children that are React components nested inside a parent component.

Our documentation tooling (and react-docgen under the hood) does not have a way of documenting prop types + defaults for these nested components.

Right now, we use the parent's page to document all it's children as well: https://auth0-cosmos.now.sh/docs/Form

Here are 2 approaches to create prop tables for nested components:

&nbsp;

- Create a custom prop table in the docs and pass the config manually in parent's page. The docs for `Form.Field` would look something like this:

```md
	Form is a compound component that ships with extra props for elements that take care of layout, 	styling and accessibility.

	There are common props for all fields like label, description and error.

  ``js props
	const props = {
		/** Label to show with the field */
    	label: PropTypes.string.isRequired,
		/** Description shown to give context about the field */
        description: PropTypes.string
	}
  ``
```

A similar table for `Form.Actions` under that.

I see this becoming a maintenance nightmare very fast. It be useful if we can document this in the component and pull it in to the docs. react-docgen doesn't support this, it might not be the best of ideas to create a custom implementation for this. 

&nbsp;

This brings us to the second proposal.

- Document each child in it's own page

If we create a file for each nested component inside a compound component, we can document propTypes inside that and use our current tooling with minor UI tweaks.

![screen shot 2018-01-31 at 9 22 09 am](https://user-images.githubusercontent.com/1863771/35604791-13f151c2-066a-11e8-9ce1-913669ff5ada.png)

Pros:
- No change in tooling
- Quick to document (we already know how to use it)

Cons:
- Extra navigation for doc users. The parent doc gives examples of usage but links out for more details.
- Complex component code. Creating a React component (with separate file) will create some indirection in the code, especially because child components will almost always export a `StyledChild` as well because the parent controls the layout.

&nbsp;

I'm lost for ideas here. Leaning towards the 2nd approach because at least it works™

**Comment by nkohari** [comment]
IMO, I think the second approach is better. I think sticking with one (public) component per file is a really good practice; otherwise things can get really confusing long-term. I actually ran into this yesterday in `<Sidebar>` to do this with `<Sidebar.Link>` and `<Sidebar.LinkGroup>` but I wasn't sure how to handle the documentation.

As far as the `StyledChild` export, I think the best strategy I've seen is standardizing on something like this:

```jsx
const MyComponent = props => (
  <MyComponent.Element>
    ...
  </MyComponent.Element>
)

MyComponent.Element = styled.div`
  /* styles here */
`

export default MyComponent
```

We can use another name than `Element` (something like `Wrapper` would also be fine?), but from what I've seen this is the cleanest way to manage the exports.

**Comment by siddharthkp** [comment]
> IMO, I think the second approach is better. I think sticking with one (public) component per file is a really good practice

👍

I like using `StyledChild` export + import in the system because it's easier to spot components that are being controlled by external/parent components. 

`MyComponent.Element` is cleaner, always present, but removes that predictability for me. That might just a bias in the back of my head.

**Comment by nkohari** [comment]
Honestly, I think my concern with the other approach might just be the naming. Most of my experience is with OOP, so `StyledComponent` seems like a sub-class of `Component`. :)

Here's a solution that might be the best of both worlds:

```jsx
const Sidebar = props => (
  <SidebarElement>
    ...
  </SidebarElement>
)

const SidebarElement = styled.div`
  /* styles */
`

export default Sidebar
export SidebarElement
```

What do you think?

There's also situations where we may want more than one styled element inside of a component. For example, [here's the SidebarLinkGroup with some changes I proposed](https://github.com/auth0/cosmos/blob/b3819a854dca350b4634b9b1b859e9e035ffca92/src/components/molecules/sidebar/sidebar-link-group.js). To actually alter the styling of the `<SidebarLinkGroup>` you'd need to deal with the `SidebarLinkGroupContent` rather than the `SidebarLinkGroupElement`. Should we try to handle this case also?

On the original topic of compound components, you can also see what I came up with for structuring the sidebar [here](https://github.com/auth0/cosmos/blob/b3819a854dca350b4634b9b1b859e9e035ffca92/src/components/molecules/sidebar/index.js#L15). This feels pretty clean to me, but I'm not sure about the documentation aspect.

**Comment by siddharthkp** [comment]
I'm cool with either (consistent) naming convention. `SidebarElement` makes sense to me.

> Should we try to handle this case also?

If the children have their own props, then I feel we'll have to 😢 

👍 `Sidebar.Link = SidebarLink` is exactly what I had in mind

**Comment by nkohari** [comment]
Cool! Let's standardize on the multiple exports, with (for example) `Sidebar` and `SidebarElement`. That feels like the best of both approaches.

In situations where a component has multiple inner elements, maybe we standardize on `Element` being the outer one, and `Content` being the inner one? So for `SidebarLinkGroup` it'd be:

```
const SidebarLinkGroup = props => (
  <SidebarLinkGroupElement>
    <SidebarLink ... />
    <SidebarLinkGroupContent>
      {props.children}
    </SidebarLinkGroupContent>
  </SidebarLinkGroupElement>
)

const SidebarLinkGroupElement = styled.div`
  /* styles */
`

const SidebarLinkGroupContent = styled.div`
  /* styles */
`

export default SidebarLinkGroup
export SidebarLinkGroupElement
export SidebarLinkGroupContent
```

Does this seem ok? Happy to standardize on something else too, I think consistency is the most important thing. :)

**Comment by siddharthkp** [comment]
Err, this is awkward. It sounds generic enough but would break in some ugly corner.

I like switching from StyledLink to LinkElement because it's 1:1. 

Adding children makes me feel underconfident, like, 

1. should they be components of their own?
2. should they be allowed to style by the parent across 2 levels of nesting? (parent can pass props to child which styles it's own child)

**Comment by siddharthkp** [comment]
P.S. Also can we change the convention after the POC, there are a bunch of places that already use `Styled...`

**Comment by nkohari** [comment]
Yeah... I agree about the children naming. Maybe you're right in that it's a code smell if we encounter that situation, and we should just avoid it.

And yes, I also agree that we don't need to spend a whole lot of time on (internal) code quality improvements before the POC is finished! :) It might be good to take a little time after we wrap it up to tackle some things like this though.

**Comment by siddharthkp** [comment]
We figured this out and it's LIVE!

**Comment by landitus** [comment]
Awesome! 🎉
