### ISSUE TITLE
[Form] Remove destructive actions from FormInputs

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#239]

**Comment by nkohari** [comment]
@landitus Could you add more info to this?

**Comment by landitus** [comment]
Yes. In order to blend in the current production code of Manage, I’ve decided to dial back on design changes for the PoC. We’re only changing what makes sense to correct by using tokens to achieve a more consistent design: color, spacing, etc. While building the PoC I’ve came to realize that some design changes (like this one) need to be well resolved by the product design team and documented before committing to code the component in the DS. This was a wake up call to not change the design without actually going through a process that will ensure the component is well defined first. 

I won’t lie it’s been hard to see what designs to change or what not. So, the rule now is to keep it to the minimum. this will ensure we can blend into the products. That means removing this destructive action from the Form Actions API and building the destructive area component instead.

More radical design changes will happen eventually and we’re looking into the right approach with the Product design team.

**Comment by siddharthkp** [comment]
Removed from `Form.Actions` in https://github.com/auth0/cosmos/pull/262. We are keeping `<Button destructive/>` right?

**Comment by landitus** [comment]
Yep, we are keeping  the `<Button destructive/>`

**Comment by nkohari** [comment]
Closed by #262.
