### ISSUE TITLE
Create visual diff system v2

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#362]
One of the critical features that Cosmos components provide is consistency of visual appearance. In order to guarantee that, we need to be able to visually compare versions of Cosmos to ensure nothing has changed. To do this, we need to create a "visual diff" system which will be run as part of the automated test battery.

For Cosmos 0.1, the goal is to create the first version of this system, and evaluate how we want to manage it going forward.

**Comment by siddharthkp** [comment]
Okay, this is a big one, So I'll have to break this down into smaller units.

Here's my long thought process around visual diffs:

#### Why?

See what has changed, so that

- the developer can see if there are any unintentional changes made
- the reviewer can see what has changed and identify any unintentional change.

#### Output

- A screenshot of before, after and [visual diff between them](https://raw.githubusercontent.com/mapbox/pixelmatch/master/test/fixtures/4b.png)  of all the components that have changed.
- A way to approve changes (overkill?)

**Comment by siddharthkp** [comment]
#### Implementation details:

#### v1:

- Use Overview page for diff
- Run command manually to generate screenshots
- Commit diff to repository

Problems: 
1. Diff is only useful if master is always up to date.

#### v∞:

**Comment by siddharthkp** [comment]
I guess this is an umbrella now

**Comment by siddharthkp** [comment]
I think we can close this issue 😄
