### ISSUE TITLE
Standardising actions in Form Actions

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#390]
Maybe we should make it more standard and have `SecondaryAction` in singular and make it accept only one button. I don't think we'll need multiple secondary actions for now.

<img width="864" alt="screen shot 2018-03-09 at 15 51 15" src="https://user-images.githubusercontent.com/239215/37224268-bbdcb458-23b1-11e8-8b96-ad09a8ff79b6.png">

wdyt?

**Comment by nkohari** [comment]
Related to the conversation about standardizing the concept of `Action` (see #189), what do you think about something like this?

```jsx
<Form.Actions actions={[
  new Action({ appearance: "primary", label: "Save Changes", method: () => {} }),
  new Action({ appearance: "default", label: "Clear", method: () => {} })
]} />
```

Or, more succinctly, something like:

```jsx
<Form.Actions actions={[
  Action.primary({ label: "Save Changes", method: () => {} }),
  Action.default({ label: "Save Changes", method: () => {} })
]} />
```

We can work on the particulars of the API, but the general ideas is that this `Action` object can be used anywhere we have this concept, including Forms, Dialogs, and Inputs.

**Comment by siddharthkp** [comment]
I really like the concept of `new Action` but I'd say it's a building block and should not be part of the API of compound components.

`actions={[]}` is pushing towards composability, maybe this is a rigid/locked component. 

Example:

```jsx
<Form.Actions actions={[
	Action.default({ label: "Save Changes", method: () => {} }),
	Action.primary({ label: "Clear", method: () => {} }),
]} />
```

`default` before `primary`, would this be allowed?

How about: 

```jsx
<Form.Actions actions={[
    Action.primary({ label: "Save Changes", method: () => {} }),
	Action.link({ label: "Clear", method: () => {} }),
]} />
```

I'd expect this to work and a render a `Link` button.

----

It seems a common trend in our API: Whenever we want to lock the API, we should accept `data` in `props`. When we want composability, we should expose child components like `Form.Field`.


Now that only 2 actions are possible, how about:

```jsx
<Form.Actions
  primary={{ label: "Save Changes", method: () => {} }}
  secondary={{ label: "Clear", method: () => {} }}
/>
```

**Comment by nkohari** [comment]
> default before primary, would this be allowed?

I think it would be up to the component how it wanted to render the actions. For example, it might be a rule for `Form.Actions` that primary actions always come first.

> I'd expect this to work and a render a Link button. But, are Link buttons allowed in forms actions?

Definitely a fair point. This does result in a more open API, which isn't necessarily a good thing. :)

I like the proposal in the last code block, with `primary` and `secondary` options. I'd still push for there to be an `Action` constructor (or static method) being called so we can use `PropTypes.instanceOf()` instead of `PropTypes.shape()`, but that's my strong-typing bias showing. 😄

In general, I think when there's an opportunity to give something that's reused a common name, it makes working with the individual components easier. Once someone understands what an `Action` is, whenever they encounter another component that accepts an `Action` as a prop they are already familiar with how to use it.

**Comment by nkohari** [comment]
The first one means we still end up with "duck typing" (that is, `PropTypes.shape()` rather than `PropTypes.instanceOf()`) in the API, but that's okay if that's what we want. :)

**Comment by siddharthkp** [comment]
Whoops, that's totally my untyped languages bias.

- Is there difference in error messages that we display? (I'm not able to guess, I can try this out)

- Can we get the same quality of error by using `Proptypes.shape(_Action)`?

**Comment by nkohari** [comment]
Closing in favor of #600, which describes the remaining action that needs to be taken.
