### ISSUE TITLE
Avatar spec needed

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#406]
I don't know what's expected from the `Avatar` component, how many types of avatars exist, what design aspects should be locked and what should be cusomizable (background-color, shape, size, etc.)

There is some discussion here: https://github.com/auth0/cosmos/pull/398

**Comment by landitus** [comment]
I did a small inventory for the **Avatar**: 

<img width="751" alt="screen shot 2018-03-14 at 17 02 35" src="https://user-images.githubusercontent.com/239215/37428748-fcd552a0-27ab-11e8-8d81-f80452fb0c90.png">

### The User Avatar:
The default user avatar has a letter or 2, and a random background color. The color stays with you, so it's not random for each rendering. I was talking to @vctrfrnndz and he was telling me that this default lettering system is actually pulling images from the CDN will all possible single and double letter combinations with a random color. This is because we are using gravatar and the fallback should be an image (not a text inside a circle). Maybe we need to dig deeper into this. 🧐

If the user has an image, it will render the photo to fill the circle.

### The Image for an entity:
For an API or Client or Connection. It's a full image with no background. It has rounded corners and a border. I would expect the image fill the square. We should have a background color of gray as a fallback, for loading purposes.

There is a special case where an icon (from our library) is used inside the square to represent an entity. We should be able to achieve this too.

### Ideas
Have 2 components: `Avatar` and `Thumbnail`. Move forward with the Thumbnail and figure out the Avatar later?

**Comment by landitus** [comment]
Sometimes this inventory / discovery can lead up to think or propose a change in the **design**  to condense disconnected UI design decisions. I wouldn't discard this, as when we do componentization work, it's useful to do some cleanup.

**Comment by beneliflo** [comment]
`Thumbnail` love it. That is perfect name to this component and it's easier to identify it and differentiate it with the user avatar.

**Comment by landitus** [comment]
In this case, the thumbnail has an outline (gray) but inside can be either an image or an icon. So, when we want to show a logo for inside a table, we should use the Thumbnail to add the image.

For example, here:
<img width="901" alt="screen shot 2018-03-16 at 19 07 38" src="https://user-images.githubusercontent.com/239215/37546784-55a84cd2-294d-11e8-9613-e38aa61c2fbd.png">

**Comment by landitus** [comment]
Love if the avatar could handle the Gravatar logic! We should first check how it's done today

**Comment by astanciu** [comment]
Wanted to add another Avatar to the inventory:
![image](https://user-images.githubusercontent.com/1675025/38379067-9636e404-38cd-11e8-9023-0fd6802b0ea2.png)

Having the option of adding Name and email (linkable) would be great

**Comment by landitus** [comment]
Thanks @astanciu !

**Comment by nkohari** [comment]
Closed by #561.
