### ISSUE TITLE
Spacing and tooltips in ButtonGroup are incorrect

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#517]
There's a bug in the Button Group component that breaks the layout when adding labels to the buttons. One a label is declared, the buttons collapse the spacing.

<img width="426" alt="screen shot 2018-04-23 at 19 30 28" src="https://user-images.githubusercontent.com/239215/39156503-d54532d2-472c-11e8-905a-214051c128b1.png">

**Comment by landitus** [comment]
I believe there are is a :last-child class being triggered because of the tooltip wrapper

**Comment by nkohari** [comment]
I'm going to piggy-back on this issue since I think it's related to the new bug we found with the tooltip alignment. In a `ButtonGroup`, the tooltips for the buttons are misaligned, since they take into account the left margin. For example:

![screen shot 2018-04-24 at 8 37 53 am](https://user-images.githubusercontent.com/1576/39187362-1ceb9504-479b-11e8-8a59-321175335714.png)

It might be tough to see, but the tooltip is just slightly to the left of center.
