### ISSUE TITLE
Fix columns on ResourceList

### ISSUE THREAD

**Issue by astanciu** [auth0/cosmos#523]
Have some feedback on the new ResourceList component:

- Improve handling of large subtitle. Currently there is a bug that causes this:
![image](https://user-images.githubusercontent.com/1675025/39328248-c8fa963c-4968-11e8-9aa5-925553143ebc.png)

Ideally, it would look like this:
![image](https://user-images.githubusercontent.com/1675025/39328494-8c2a6e2a-4969-11e8-83a4-a065cf214efd.png)

- Row or Title click handlers...  would be very helpful to allow making the row or title clickable, in addition to the actions. Ex, clicking the row could take you to a child page with the item's details, while the quick actions are for immediate actions...

**Comment by vctrfrnndz** [comment]
IMO, part of this is a design flaw in the component. We need to change to something more generic from our current "all caps" design (meant only for short phrases or labels) in order to be able to support longer or texts with other purposes.

I suspect the collapsing of the text is also because the component supports passing custom information as a "body".

**Comment by nkohari** [comment]
@landitus Do we want to change the design of this? We also discussed whether the header of a `ResourceListItem` could just be an `Avatar`.
