### ISSUE TITLE
Remove React 16 features?

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#539]
To support React 15, we need to shy away from the nice new features 😅

Found one in `Button`: https://github.com/auth0/cosmos/blob/master/src/components/atoms/button/index.js#L165-L168

Seems like manage is cool with it, should cosmos come with a React 16 pre requisite?

P.S. Pointed out in: https://github.com/auth0/cosmos/pull/538#discussion_r186680067

**Comment by nkohari** [comment]
Hm... React is already up to 16.3, and 17.x will likely be out before Cosmos hits 1.0. I think we should be targeting 16.x unless there's some reason it's impossible. So far, React has been very backwards-compatible, so there's not a lot of reason people should avoid upgrading.

**Comment by siddharthkp** [comment]
> React has been very backwards-compatible, so there's not a lot of reason people should avoid upgrading.

True!

It's just scary for people, I don't want to scare any teams away 😄

**Comment by landitus** [comment]
My concern would be that one team is still in v15 and while they are planning to upgrade, I don't think it's a priority. The question would be: who defines the version of React to be supporting? At what pace should we upgrade? Are we going to upgrade to a new version of React from a 1.3.x to 1.4.x release? Maybe the React version is tied to the Cosmos main relase (v1.x.x) and we'll consider supporting one version till a mayor Cosmos 2.x.x. 

I know React releases are not big, but nontheless, we should consider this. Just throwing some ideas.

In the case we stayed (for a long time) in v15, would it hurt adoption or perception if one or more teams started using 17 or onwards?

**Comment by itaditya** [comment]
@siddharthkp has anything been finalized?

**Comment by luisrudge** [comment]
I had the same issue with lock and what I learned is: react/react-dom should NOT be a direct dependency. It should be a peer dependency instead. This way, you can make sure the codebase works with react@16 & react@17. With lock, for example, I can't upgrade to react@16 without releasing a new major version because that would break current customers as well (we use react as a direct dependency too). My advice is: use react/react-dom as peer dependencies so you don't end up in a never-ending cycle of "please upgrade to react@latest" and "why my app upgraded to react@latest?".

All the big ui libraries use peer dependencies:
https://github.com/mui-org/material-ui/blob/master/package.json#L53
https://github.com/reactstrap/reactstrap/blob/master/package.json#L102
https://github.com/Semantic-Org/Semantic-UI-React/blob/master/package.json#L169

**Comment by siddharthkp** [comment]
Good point!

We don't list react as a direct dependency, but we do use some of its features 😓

For example, if we use wish to use Portals, we're expecting the app to use React 16 and above

**Comment by luisrudge** [comment]
react is listed as dependency: https://github.com/auth0/cosmos/blob/master/package.json#L19-L20

You can specify the peer dependency to be 16+

**Comment by siddharthkp** [comment]
That's the project's dependencies. That's not what is installed when you say `npm install @auth0/cosmos`, this is the [package.json to look at](https://github.com/auth0/cosmos/blob/master/src/components/package.json)

> I don't think it's worth it to worry about people running react 15.

That's good to hear 😄

**Comment by siddharthkp** [comment]
@landitus @nkohari With our new adoption strategy, I think it's uncontroversial to enforce React 16. what do you think?

**Comment by nkohari** [comment]
@siddharthkp I agree. If there's a way we can handle it using peer dependencies that won't make things more difficult for users, I think that's a reasonable approach. Otherwise we should just make 16.x the minimum. If React was on 16.0 I might feel differently, but they're already on 16.4, so I think requiring 16.0 is reasonable.

**Comment by luisrudge** [comment]
what's the new adoption strategy?

**Comment by landitus** [comment]
😎 Let's move this to a discussion and check with other teams what's the version and plans to upgrade
