### ISSUE TITLE
Usability testing: Forms

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#795]
You can drop your feedback in this issue as comments and close it when you're done!

We'll create new issues for changes to be done.

Things to remember: Fields, Actions, Fieldset, Errors, Submitting

What makes a component _good_ for usage? See https://github.com/auth0/cosmos/issues/794

**Comment by francocorreasosa** [comment]
- Form Input action is not vertically centered 
- Inside a form, we don't support different form layouts between different fieldsets (probably intentional)
- `Form.Radio` example does not work on docs

<img src="https://user-images.githubusercontent.com/4152942/44356106-cacef800-a484-11e8-8954-8c9f424b6d78.png" width="220px" />
