### ISSUE TITLE
Alert title styles problems and making it optional

### ISSUE THREAD

**Issue by astanciu** [auth0/cosmos#895]
The title attribute on the Alert component is hard to read and cannot be removed since it's a required prop:

![image](https://user-images.githubusercontent.com/1675025/45124038-e00b7e00-b136-11e8-9a6d-ad933ccec63e.png)

some suggestions:
- make it optional
- make it bold with more margin on the right?

![image](https://user-images.githubusercontent.com/1675025/45124163-48f2f600-b137-11e8-84be-3e59fba808df.png)

**Comment by landitus** [comment]
Thanks for reporting!

I see this is part of the issue with global styles and some overrides in
manage. So there is some rendering differences, probably due to conflicting
styles in manage. We are going to fix this in the alert by adding more
specific styles so it looks like it should.


On 5 Sep 2018 at 19:21, Javier Centurion <notifications@github.com> wrote:


@astanciu <https://github.com/astanciu>, the following code

<Alert type="danger" title="API Error" dismissible>Bad Request</Alert>

should render like:

[image: image]
<https://user-images.githubusercontent.com/302314/45124380-78f2c700-b140-11e8-8697-44cd1d74ac26.png>

Are you seeing the following in manage?

<https://user-images.githubusercontent.com/1675025/45124038-e00b7e00-b136-11e8-9a6d-ad933ccec63e.png>

Which version of Cosmos are you using?
------------------------------

Regarding to make title optional, you can use title="".

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/auth0/cosmos/issues/895#issuecomment-418900601>, or mute
the thread

**Comment by landitus** [comment]
What version of cosmos are you using @astanciu ?

**Comment by astanciu** [comment]
v0.3.3

**Comment by landitus** [comment]
Ok! So, 0.4 introduced a different global/resets strategy that fixes these kinds of issues. The alert, in particular, has an issue with the title style that will still need to fix. So this issue will track that.

**Comment by landitus** [comment]
I'm closing this one as all issues have been solved: title is optional and also renders correctly as strong text.
